sudo: required
language: minimal
services:
- docker
env:
  global:
  - DOCKER_USER=booooza
  - secure: P63nsiS1c0oOMFFHLm/wkBe08jzppijW2bbFGCh8EcV14j8E2WA2c7L7Xs4CmLUKbP+2pXbvpZkl0XfVEkNEmMXDSIUd2dpKR4nr2XwhihCIp5yt6h/2YQY/yBaTXOpeQ0GLDaut6rWgRwpSxv9Pf5QQx/F9ACvUbwR+O8RfUcuTQxZ2XM+OX4CmhITJcskunDP0R/3Js8uIl8dYw8E2bEAQY4nZDkPEOuX+Y1FMBnSGktIdJ2vdQXOnqm5HCu/rzaDBZp5Jma8qJsvbdUDq+dejvR3BEajD7hIS7UZfBCBG5lqcylGKh50GZSEGgJz7Dei+ZKLOeq1+Fnu+cGMnS+HMkU+M5/AK2HSm7+6hat0YtqfDL6Ny5+GvY+HrlE07XAa+hzOaALoNr5Sod1kBbZVNsO9FgoJjaXj/ZCy56ch1FcCW5xXVs6//tgO3C+rSMYUWQS/LGLmxTx04iAJoPOAlGd4CkKSJBoAO0qTI5jvUaj86TE5Px1/Wo0zdKz8oCM8+3Towq2ocIDmy0P3VCummrVrwI1DPLEF4UMyaN/+X0194UaecE6FJmxqchah7IUnTnlzkhIkLm4QlptFKoKo7bOyDKcldH3gfvJB4iNDzFOLjT4F1XbHAw3ticNbMf1z1r0xYoha7fz5QedD0CDc0NzabpHoCSFzBBQrm7lA=
  - BLUEMIX_USER: booooza@gmail.com
  - secure: "EzUB7cfuk3t1Ve1sxpKa0twzSf2RH8MnjC6w7jl4sr7Kl/Iusr3q5ALSBgtbB6e30cpjdgPeBzDnU71WSIjmRW2Q0LBuu7ReIsQ/HkOHsrIdhYW0RjNFT443wiMdmap+FnQaFb0BlQZUpFhEYQ8+2eXCKJMf/fzr8/VqRfBi93CgoK1EnvReGXMYa5gKrVtbx2X7zEDUA/erm6OD0RrSbd2PEUsCP+ee84kvFcvAKNAFA9vPQLnJgk5QCspdfZ7BzGjsMTSAccPgOsGd/vpj5EVU/fQprDcFUm6y88gEfIxixCKztc28uAc8ELvcoM2vZiDZIIAfi+FnYdj3FaV+6VffyV7HT37vEDGw7Kdj6F6FrO0ihaSo5JeB9+2BDS6M23EgmuzGJSyb3b2gOYv3gA3ASEAaRrBloMyx9dz8Kljl5xPXgBhV4O6WTP+xQMOLMmjj586WlJX3MRcKDo4dHEpaB9j9pIERrk+aFzJOiiIbZFgTj5z2rBN7PdGpbVxchbX3qih4LYfDGr8FWKiAmIhC2hUyceVXj7OFJx4nDjgYN3PyTysrQZ1+v9z7d0V1cvhzcnOtmEc7lGUZ5nooEGDYdMAYUDPsOM2MvzGxeNblssOMwxl2YMiOjzut/dpwp5aocaPnlWR5u7mHB+0qVzV/u0OMA/tuTvRE2iOdF/A="
  - BLUEMIX_ORGANIZATION: cf-react-cicd-demo
  - BLUEMIX_SPACE: cf-react-cicd-demo
install: false
jobs:
  include:
  - stage: build docker image
    script:
    - docker build -t cf-react-cicd-demo .
    - docker tag cf-react-cicd-demo $DOCKER_USER/cf-react-cicd-demo
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker push "$DOCKER_USER"/cf-react-cicd-demo
  - stage: deploy to bluemix
    script:
    - ./deploy.sh
